# Generated by Django 4.1.7 on 2023-07-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='categorydata',
            new_name='categorydb',
        ),
    ]
