# Generated by Django 4.1.7 on 2023-07-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_categorydata_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='venuedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VenueName', models.CharField(blank=True, max_length=50, null=True)),
                ('venueAddress', models.CharField(blank=True, max_length=100, null=True)),
                ('venueRent', models.CharField(blank=True, max_length=50, null=True)),
                ('venueDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('venueImage', models.ImageField(blank=True, null=True, upload_to='Venues')),
            ],
        ),
    ]
