# Generated by Django 4.1.7 on 2023-07-25 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_venuedb'),
    ]

    operations = [
        migrations.CreateModel(
            name='cateringdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catname', models.CharField(blank=True, max_length=50, null=True)),
                ('catrent', models.CharField(blank=True, max_length=50, null=True)),
                ('catDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('catImage', models.ImageField(blank=True, null=True, upload_to='catering')),
            ],
        ),
    ]
