# Generated by Django 4.1.7 on 2023-07-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_cateringdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='mediadb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medianame', models.CharField(blank=True, max_length=50, null=True)),
                ('mediarent', models.CharField(blank=True, max_length=50, null=True)),
                ('mediaDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('mediaImage', models.ImageField(blank=True, null=True, upload_to='photography')),
            ],
        ),
        migrations.CreateModel(
            name='transportationdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transname', models.CharField(blank=True, max_length=50, null=True)),
                ('transrent', models.CharField(blank=True, max_length=50, null=True)),
                ('transDescription', models.CharField(blank=True, max_length=500, null=True)),
                ('transImage', models.ImageField(blank=True, null=True, upload_to='transportation')),
            ],
        ),
    ]
