# Generated by Django 4.1.7 on 2023-08-03 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_mediadb_transportationdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediadb',
            old_name='mediaImage',
            new_name='mediapic',
        ),
    ]
