# Generated by Django 4.1.7 on 2023-08-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_rename_mediaimage_mediadb_mediapic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringdb',
            name='catrent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediadb',
            name='mediarent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportationdb',
            name='transDescription',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transportationdb',
            name='transrent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='venuedb',
            name='venueRent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
