# Generated by Django 4.1.7 on 2023-08-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_cateringdb_cataddress_mediadb_mediaaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=50, null=True)),
                ('service_address', models.CharField(blank=True, max_length=100, null=True)),
                ('service_rent', models.IntegerField(blank=True, null=True)),
                ('service_description', models.CharField(blank=True, max_length=500, null=True)),
                ('service_image', models.ImageField(blank=True, null=True, upload_to='transportation')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.category')),
            ],
        ),
        migrations.DeleteModel(
            name='categorydb',
        ),
        migrations.DeleteModel(
            name='cateringdb',
        ),
        migrations.DeleteModel(
            name='mediadb',
        ),
        migrations.DeleteModel(
            name='transportationdb',
        ),
        migrations.DeleteModel(
            name='venuedb',
        ),
    ]
