# Generated by Django 4.1.7 on 2023-08-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_remove_service_category_alter_service_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_rent',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
