# Generated by Django 4.1.7 on 2023-08-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_alter_service_service_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_rent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
