# Generated by Django 4.1.7 on 2023-08-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_alter_service_service_rent'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
