# Generated by Django 4.1.7 on 2023-08-10 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_service_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='c_name',
        ),
    ]
