# Generated by Django 4.1.7 on 2023-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_rename_name_service_c_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='c_name',
            field=models.CharField(max_length=50),
        ),
    ]
