# Generated by Django 4.1.7 on 2023-08-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_alter_service_c_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='c_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
