# Generated by Django 4.1.7 on 2023-08-10 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_rename_c_name_service_x_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='x_name',
            new_name='s_name',
        ),
    ]
