# Generated by Django 4.1.7 on 2023-08-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_rename_x_name_service_s_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(default=1, upload_to='category_logo'),
            preserve_default=False,
        ),
    ]
