# Generated by Django 4.1.7 on 2023-08-14 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
