# Generated by Django 4.1.7 on 2023-08-17 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_delete_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
