# Generated by Django 4.1.7 on 2023-08-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('availability', models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable')], max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
