# Generated by Django 4.1.7 on 2023-08-18 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0031_booking_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking_data',
        ),
    ]
