# Generated by Django 4.1.7 on 2023-08-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='cpwd',
        ),
    ]
