# Generated by Django 4.1.7 on 2023-08-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_contactdb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactdb',
        ),
    ]
