# Generated by Django 4.1.7 on 2023-08-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_contactdb'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactdb',
            new_name='Contactdata',
        ),
    ]
