# Generated by Django 4.1.7 on 2023-08-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_feedback_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='service',
            new_name='select_service',
        ),
    ]
