# Generated by Django 4.1.7 on 2023-08-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_remove_feedback_select_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='select_service',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
