# Generated by Django 4.1.7 on 2023-08-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_feedback_select_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(blank=True, max_length=50, null=True)),
                ('book_email', models.CharField(blank=True, max_length=50, null=True)),
                ('book_date', models.DateField(auto_now_add=True)),
                ('book_rent', models.IntegerField(blank=True, null=True)),
                ('book_service', models.CharField(blank=True, max_length=50, null=True)),
                ('book_message', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
